name: magicepaperapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: '3.35.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  # nfc_manager: ^3.5.0
  flutter_nfc_kit: ^3.5.2
  convert: ^3.1.2
  flutter_svg_provider: ^1.0.7
  matrix2d: ^1.0.4
  image: ^4.3.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  app_settings: ^6.1.1
  fluttertoast: ^8.2.12
  pro_image_editor: ^9.4.1
  gal: ^2.3.1
  file_saver: ^0.2.14
  bot_toast: ^4.1.3
  media_kit: ^1.2.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  file_picker: ^10.1.2
  flutter_colorpicker: ^1.1.0
  mime: ^2.0.0
  mobile_scanner: ^7.0.1
  barcode_widget: ^2.0.4
  intl: ^0.20.2
  path_provider: ^2.0.15
  get_it: ^8.0.3
  path: ^1.9.1
  permission_handler: ^11.0.1
  ndef: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/displays/
    - assets/canvas/
    - assets/icons/
